[package]
name = "parsnip"
version = "0.1.0"
edition = "2021"

[lib]
name = "parsnip"
path = "src/lib.rs"

[[bin]]
name = "parsnip-cli"
path = "src/main.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ulid = "1.0"
anyhow = "1.0.71"
redis = "0.23"
